### ISSUE TITLE
Handle edge case of old refresh tokens not working to generate new access token

### ISSUE THREAD

**Issue by seanwendt** [Better-Playlists/better-playlists-web#9]
![image](https://github.com/Better-Playlists/better-playlists-web/assets/7527192/6744b279-9f98-4913-a85a-1de275f8aa4a)

**Comment by braincomb** [comment]
So the client makes an assumption that a POST request to refresh the token will always be successful and we don't do any checking after that. I think we need anticipate this error, possibly clear localStorage (I'm not sure if there's a better way) and then retry the attempt.
